In [42]:
%run -i ../python/common.py
# setup for examples
setupExamples("inforep", "../src/Makefile ../src/empty256.s ../src/setup.gdb")

# Representing information - The Basics: Bits, Bytes and Notation


In general most physical components of a computer store, transmit, or operate on a pattern of binary values. The pattern is a fixed size collection of bi-stable physical units. Bi-stable means that each unit within the collection can reliably take on one of two distinct states. Depend on the device various different physical mechanisms can be used to represent the values. Some devices, such a older hard drives, use magnetic polarity — north vs south magnetic force. In these devices a surface is coated with a magnetic material. By dividing the surface into non overlapping regions we form units that individual and independently can have their magnetic polarity changed and detected. Integrated into these devices is one or more electro-magnetic heads that can “write” or “read” a region, when the region is below them. Writing means setting the regions polarity to north or south and reading means detecting the regions current polarity. The head is an electrical device. When reading it generates either a high or low voltage on a wire depending on the polarity of the region. Similarly an electrical signal can be used to direct it to set the polarity if desired.

Modern Solid State Drives (SSDs) and things like “USB sticks” contain electrical cells that serve as their units. No head is required for these devices as the cells can be directly accessed. Depending on the technology used the cells might represent states using electrical charge or changes in their electrical resistance.

Other devices such as memory “chips” use cells that actively consume electricity to maintain there values. If electricity is lost, eg your battery dies, then their values are lost. However, unlike Hard drives, SSDs and USB sticks, devices composed of these chips can be written and read very fast using electrical voltages on wires that are directly connected to them. These components are often called the Memory or RAM (Random Access Memory) of our computers. The CPUs have direct electrical connectivity to them and they serve as the working memory for the active programs running on our computers.

From our perspective the key point is that regardless of the technology storage devices and can be abstractly though of as a fixed size array of units that can take on of one two distinct states\footnote{}. Further the devices can be controlled and accessed through electrical signals.


This last part is important as the majority of high speed devices, like RAM and the CPUs, used in a computer use electricity or in some cases light. High vs low electrical voltage is in some sense the universal language for binary values in a computer. Circuits within the CPU operate on electrical voltages to implement functions on the patterns. Collections of wires, called buses, interconnect components of the computer and allow them to transmit patterns between each other in controlled and orderly ways. Like most things the transfers are initiated and controlled via the the instructions of our programs execute by the CPU. For example
the following two Intel instruction sequence directs the components of the computer to transmit 64 binary values from one location in RAM to another via a register in the CPU.
```
mov rax, qword ptr [4208]
mov qword ptr [4216], rax
```
Even our I/O device such a touch screen is really just a device which electrical charges can be used to control the individual picture element (pixels).  Specifically turning on or off specific light emitting components (such as Light Emitting Diodes). Or translate pressure on the screen into electrical signals on wires for the particular location touched.

While the physical part of the computers can store (eg RAM), transmit (eg Busses) and operate on (eg CPUs) binary patterns via electrical voltages they do not enforce a particular "meaning" on the patterns. In some sense the components of the computer form a blank sheet of “paper” which a programmer can use to represent and manipulate information using patterns of electrical signals and the capabilities of the CPU, memory and I/O devices.

## Information

Given that the components of a computer are built to work with discrete binary, two valued, patterns it is natural for us to use arrays of binary digits (bits) to represent what values we want the components to store or the operations we want done.

As such the world of software is really a world in which we translate our ideas into arrays of bits. Remember, however, as we continue our discussion of information representation the components of the computer are simply working on patterns of electrical signals, charges, resistance, magnetic polarity, etc. They do not store or operate explicitly on strings, integers, floats, functions, instructions, hexadecimal values or even ones and zeros. All these things are how we as programmers use the values within the components to represent information (including the instructions of our programs that implement algorithms).

<a id="THEBYTE_sec"></a>
### The Byte

In [15]:
display(Markdown(htmlFig("../images/8switches.png",id="fig:8switches", width="70%",
                         caption="Fig: A byte as 8 switches: We can visualize a byte as an array of 8 bits.  As a programmer we think of a computer as many such arrays.  Each byte has some particular location in the computer and a particular value that it current stores.  The value can be though of as the current configuration of its switches. ")))

<!-- produced by:
htmlFig("[{'src': '../images/8switches.png'}]",
        id="fig:8switches",
        align="center",
        width="70%",
        margin="auto auto auto auto",
        caption="Fig: A byte as 8 switches: We can visualize a byte as an array of 8 bits.  As a programmer we think of a computer as many such arrays.  Each byte has some particular location in the computer and a particular value that it current stores.  The value can be though of as the current configuration of its switches. ",
        captionalign="left")
-->
<table id="fig:8switches" align="center" width="70%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: auto auto auto auto">
    <tr style="padding: 0; margin: 0;">
        <td colspan="1" width="100%" style="padding: 0; margin: 0 0 0 0; background-color:inherit;">
            <div style="padding: 0; margin: 0 0 0 0;">
              <figure style="padding: 0; margin: 0 0 0 0; width:100%;">
                   <img src="../images/8switches.png" width="100%" style="padding: 0; margin: 0;">
                </figure>
            </div>
        </td>
    </tr>
    <caption align="bottom" style="text-align: left; padding: 0; margin: 0;" >
          <i>Fig: A byte as 8 switches: We can visualize a byte as an array of 8 bits.  As a programmer we think of a computer as many such arrays.  Each byte has some particular location in the computer and a particular value that it current stores.  The value can be though of as the current configuration of its switches. </i>
    </caption>
</table>

The standard unit that we have settled on is a pattern of 8 bits, binary digits, called a byte. Some times we break a byte down into two 4 bit quantities called a nibble. Bytes are also often grouped into larger units. The names for these larger units, however, unfortunately are not always consistent. Some conventions, such as those used Intel products, call a array of two bytes is a *word*, four bytes a *double word* and 8 bytes a *quad word*. However other conventions refer to four byte arrays as a *word*, a two byte arrays as *half word* and an 8 byte array as a *double word*. Given this ambiguity it is often best to use bit lengths such as 8, 16, 32, 64, 128, 256 to avoid confusion. However, sometimes we don not have a choice but to be aware of the convention that is in use to understand what is meant by the code or manual we are reading.

In [16]:
md=displayBytes(bytes=[[i] for i in range(256)], 
             td_font_size=".5em", th_font_size=".7em", 
             center=True,disp=False)
#use a MDBox to force height controll and place floating title
display(Markdown(
    MDBox(md, 
          title='<center id="table:allbytevals" style="font-size:.8em">Table of all <em>2<sup>8</sup> = 256</em> possible binary byte values.</center>', 
          h="10em")
  )
)

<center id="table:allbytevals" style="font-size:.8em">Table of all <em>2<sup>8</sup> = 256</em> possible binary byte values.</center>
<div style="width:100%; height:10em; font-size:inherit; overflow: auto;" >

<style type="text/css">
#T_b92ab td {
  border: 4px solid #cccccc;
  font-size: .5em;
  text-align: center;
  overflow-x: hidden;
}
#T_b92ab th {
  font-size: .7em;
  text-align: center;
  font-weight: bold;
  border: solid #cccccc;
  color: black;
  background-color: white;
}
#T_b92ab td:hover {
  background-color: white;
  color: black;
}
#T_b92ab tr:hover {
  background-color: #11cccccc;
  border: 4px solid red;
}
#T_b92ab th:hover {
  border: solid red;
}
#T_b92ab thead tr:nth-child(1) th {
  position: sticky;
  background-color: white;
  top: 0px;
  z-index: 2;
}
#T_b92ab  {
  margin-left: auto;
  margin-right: auto;
}
</style>
<table id="T_b92ab">
  <thead>
    <tr>
      <th id="T_b92ab_level0_col0" class="col_heading level0 col0" >[<em>b<sub>7</sub></em></th>
      <th id="T_b92ab_level0_col1" class="col_heading level0 col1" ><em>b<sub>6</sub></em></th>
      <th id="T_b92ab_level0_col2" class="col_heading level0 col2" ><em>b<sub>5</sub></em></th>
      <th id="T_b92ab_level0_col3" class="col_heading level0 col3" ><em>b<sub>4</sub></em></th>
      <th id="T_b92ab_level0_col4" class="col_heading level0 col4" ><em>b<sub>3</sub></em></th>
      <th id="T_b92ab_level0_col5" class="col_heading level0 col5" ><em>b<sub>2</sub></em></th>
      <th id="T_b92ab_level0_col6" class="col_heading level0 col6" ><em>b<sub>1</sub></em></th>
      <th id="T_b92ab_level0_col7" class="col_heading level0 col7" ><em>b<sub>0</sub></em>]</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_b92ab_row0_col0" class="data row0 col0" >0</td>
      <td id="T_b92ab_row0_col1" class="data row0 col1" >0</td>
      <td id="T_b92ab_row0_col2" class="data row0 col2" >0</td>
      <td id="T_b92ab_row0_col3" class="data row0 col3" >0</td>
      <td id="T_b92ab_row0_col4" class="data row0 col4" >0</td>
      <td id="T_b92ab_row0_col5" class="data row0 col5" >0</td>
      <td id="T_b92ab_row0_col6" class="data row0 col6" >0</td>
      <td id="T_b92ab_row0_col7" class="data row0 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row1_col0" class="data row1 col0" >0</td>
      <td id="T_b92ab_row1_col1" class="data row1 col1" >0</td>
      <td id="T_b92ab_row1_col2" class="data row1 col2" >0</td>
      <td id="T_b92ab_row1_col3" class="data row1 col3" >0</td>
      <td id="T_b92ab_row1_col4" class="data row1 col4" >0</td>
      <td id="T_b92ab_row1_col5" class="data row1 col5" >0</td>
      <td id="T_b92ab_row1_col6" class="data row1 col6" >0</td>
      <td id="T_b92ab_row1_col7" class="data row1 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row2_col0" class="data row2 col0" >0</td>
      <td id="T_b92ab_row2_col1" class="data row2 col1" >0</td>
      <td id="T_b92ab_row2_col2" class="data row2 col2" >0</td>
      <td id="T_b92ab_row2_col3" class="data row2 col3" >0</td>
      <td id="T_b92ab_row2_col4" class="data row2 col4" >0</td>
      <td id="T_b92ab_row2_col5" class="data row2 col5" >0</td>
      <td id="T_b92ab_row2_col6" class="data row2 col6" >1</td>
      <td id="T_b92ab_row2_col7" class="data row2 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row3_col0" class="data row3 col0" >0</td>
      <td id="T_b92ab_row3_col1" class="data row3 col1" >0</td>
      <td id="T_b92ab_row3_col2" class="data row3 col2" >0</td>
      <td id="T_b92ab_row3_col3" class="data row3 col3" >0</td>
      <td id="T_b92ab_row3_col4" class="data row3 col4" >0</td>
      <td id="T_b92ab_row3_col5" class="data row3 col5" >0</td>
      <td id="T_b92ab_row3_col6" class="data row3 col6" >1</td>
      <td id="T_b92ab_row3_col7" class="data row3 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row4_col0" class="data row4 col0" >0</td>
      <td id="T_b92ab_row4_col1" class="data row4 col1" >0</td>
      <td id="T_b92ab_row4_col2" class="data row4 col2" >0</td>
      <td id="T_b92ab_row4_col3" class="data row4 col3" >0</td>
      <td id="T_b92ab_row4_col4" class="data row4 col4" >0</td>
      <td id="T_b92ab_row4_col5" class="data row4 col5" >1</td>
      <td id="T_b92ab_row4_col6" class="data row4 col6" >0</td>
      <td id="T_b92ab_row4_col7" class="data row4 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row5_col0" class="data row5 col0" >0</td>
      <td id="T_b92ab_row5_col1" class="data row5 col1" >0</td>
      <td id="T_b92ab_row5_col2" class="data row5 col2" >0</td>
      <td id="T_b92ab_row5_col3" class="data row5 col3" >0</td>
      <td id="T_b92ab_row5_col4" class="data row5 col4" >0</td>
      <td id="T_b92ab_row5_col5" class="data row5 col5" >1</td>
      <td id="T_b92ab_row5_col6" class="data row5 col6" >0</td>
      <td id="T_b92ab_row5_col7" class="data row5 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row6_col0" class="data row6 col0" >0</td>
      <td id="T_b92ab_row6_col1" class="data row6 col1" >0</td>
      <td id="T_b92ab_row6_col2" class="data row6 col2" >0</td>
      <td id="T_b92ab_row6_col3" class="data row6 col3" >0</td>
      <td id="T_b92ab_row6_col4" class="data row6 col4" >0</td>
      <td id="T_b92ab_row6_col5" class="data row6 col5" >1</td>
      <td id="T_b92ab_row6_col6" class="data row6 col6" >1</td>
      <td id="T_b92ab_row6_col7" class="data row6 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row7_col0" class="data row7 col0" >0</td>
      <td id="T_b92ab_row7_col1" class="data row7 col1" >0</td>
      <td id="T_b92ab_row7_col2" class="data row7 col2" >0</td>
      <td id="T_b92ab_row7_col3" class="data row7 col3" >0</td>
      <td id="T_b92ab_row7_col4" class="data row7 col4" >0</td>
      <td id="T_b92ab_row7_col5" class="data row7 col5" >1</td>
      <td id="T_b92ab_row7_col6" class="data row7 col6" >1</td>
      <td id="T_b92ab_row7_col7" class="data row7 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row8_col0" class="data row8 col0" >0</td>
      <td id="T_b92ab_row8_col1" class="data row8 col1" >0</td>
      <td id="T_b92ab_row8_col2" class="data row8 col2" >0</td>
      <td id="T_b92ab_row8_col3" class="data row8 col3" >0</td>
      <td id="T_b92ab_row8_col4" class="data row8 col4" >1</td>
      <td id="T_b92ab_row8_col5" class="data row8 col5" >0</td>
      <td id="T_b92ab_row8_col6" class="data row8 col6" >0</td>
      <td id="T_b92ab_row8_col7" class="data row8 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row9_col0" class="data row9 col0" >0</td>
      <td id="T_b92ab_row9_col1" class="data row9 col1" >0</td>
      <td id="T_b92ab_row9_col2" class="data row9 col2" >0</td>
      <td id="T_b92ab_row9_col3" class="data row9 col3" >0</td>
      <td id="T_b92ab_row9_col4" class="data row9 col4" >1</td>
      <td id="T_b92ab_row9_col5" class="data row9 col5" >0</td>
      <td id="T_b92ab_row9_col6" class="data row9 col6" >0</td>
      <td id="T_b92ab_row9_col7" class="data row9 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row10_col0" class="data row10 col0" >0</td>
      <td id="T_b92ab_row10_col1" class="data row10 col1" >0</td>
      <td id="T_b92ab_row10_col2" class="data row10 col2" >0</td>
      <td id="T_b92ab_row10_col3" class="data row10 col3" >0</td>
      <td id="T_b92ab_row10_col4" class="data row10 col4" >1</td>
      <td id="T_b92ab_row10_col5" class="data row10 col5" >0</td>
      <td id="T_b92ab_row10_col6" class="data row10 col6" >1</td>
      <td id="T_b92ab_row10_col7" class="data row10 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row11_col0" class="data row11 col0" >0</td>
      <td id="T_b92ab_row11_col1" class="data row11 col1" >0</td>
      <td id="T_b92ab_row11_col2" class="data row11 col2" >0</td>
      <td id="T_b92ab_row11_col3" class="data row11 col3" >0</td>
      <td id="T_b92ab_row11_col4" class="data row11 col4" >1</td>
      <td id="T_b92ab_row11_col5" class="data row11 col5" >0</td>
      <td id="T_b92ab_row11_col6" class="data row11 col6" >1</td>
      <td id="T_b92ab_row11_col7" class="data row11 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row12_col0" class="data row12 col0" >0</td>
      <td id="T_b92ab_row12_col1" class="data row12 col1" >0</td>
      <td id="T_b92ab_row12_col2" class="data row12 col2" >0</td>
      <td id="T_b92ab_row12_col3" class="data row12 col3" >0</td>
      <td id="T_b92ab_row12_col4" class="data row12 col4" >1</td>
      <td id="T_b92ab_row12_col5" class="data row12 col5" >1</td>
      <td id="T_b92ab_row12_col6" class="data row12 col6" >0</td>
      <td id="T_b92ab_row12_col7" class="data row12 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row13_col0" class="data row13 col0" >0</td>
      <td id="T_b92ab_row13_col1" class="data row13 col1" >0</td>
      <td id="T_b92ab_row13_col2" class="data row13 col2" >0</td>
      <td id="T_b92ab_row13_col3" class="data row13 col3" >0</td>
      <td id="T_b92ab_row13_col4" class="data row13 col4" >1</td>
      <td id="T_b92ab_row13_col5" class="data row13 col5" >1</td>
      <td id="T_b92ab_row13_col6" class="data row13 col6" >0</td>
      <td id="T_b92ab_row13_col7" class="data row13 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row14_col0" class="data row14 col0" >0</td>
      <td id="T_b92ab_row14_col1" class="data row14 col1" >0</td>
      <td id="T_b92ab_row14_col2" class="data row14 col2" >0</td>
      <td id="T_b92ab_row14_col3" class="data row14 col3" >0</td>
      <td id="T_b92ab_row14_col4" class="data row14 col4" >1</td>
      <td id="T_b92ab_row14_col5" class="data row14 col5" >1</td>
      <td id="T_b92ab_row14_col6" class="data row14 col6" >1</td>
      <td id="T_b92ab_row14_col7" class="data row14 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row15_col0" class="data row15 col0" >0</td>
      <td id="T_b92ab_row15_col1" class="data row15 col1" >0</td>
      <td id="T_b92ab_row15_col2" class="data row15 col2" >0</td>
      <td id="T_b92ab_row15_col3" class="data row15 col3" >0</td>
      <td id="T_b92ab_row15_col4" class="data row15 col4" >1</td>
      <td id="T_b92ab_row15_col5" class="data row15 col5" >1</td>
      <td id="T_b92ab_row15_col6" class="data row15 col6" >1</td>
      <td id="T_b92ab_row15_col7" class="data row15 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row16_col0" class="data row16 col0" >0</td>
      <td id="T_b92ab_row16_col1" class="data row16 col1" >0</td>
      <td id="T_b92ab_row16_col2" class="data row16 col2" >0</td>
      <td id="T_b92ab_row16_col3" class="data row16 col3" >1</td>
      <td id="T_b92ab_row16_col4" class="data row16 col4" >0</td>
      <td id="T_b92ab_row16_col5" class="data row16 col5" >0</td>
      <td id="T_b92ab_row16_col6" class="data row16 col6" >0</td>
      <td id="T_b92ab_row16_col7" class="data row16 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row17_col0" class="data row17 col0" >0</td>
      <td id="T_b92ab_row17_col1" class="data row17 col1" >0</td>
      <td id="T_b92ab_row17_col2" class="data row17 col2" >0</td>
      <td id="T_b92ab_row17_col3" class="data row17 col3" >1</td>
      <td id="T_b92ab_row17_col4" class="data row17 col4" >0</td>
      <td id="T_b92ab_row17_col5" class="data row17 col5" >0</td>
      <td id="T_b92ab_row17_col6" class="data row17 col6" >0</td>
      <td id="T_b92ab_row17_col7" class="data row17 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row18_col0" class="data row18 col0" >0</td>
      <td id="T_b92ab_row18_col1" class="data row18 col1" >0</td>
      <td id="T_b92ab_row18_col2" class="data row18 col2" >0</td>
      <td id="T_b92ab_row18_col3" class="data row18 col3" >1</td>
      <td id="T_b92ab_row18_col4" class="data row18 col4" >0</td>
      <td id="T_b92ab_row18_col5" class="data row18 col5" >0</td>
      <td id="T_b92ab_row18_col6" class="data row18 col6" >1</td>
      <td id="T_b92ab_row18_col7" class="data row18 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row19_col0" class="data row19 col0" >0</td>
      <td id="T_b92ab_row19_col1" class="data row19 col1" >0</td>
      <td id="T_b92ab_row19_col2" class="data row19 col2" >0</td>
      <td id="T_b92ab_row19_col3" class="data row19 col3" >1</td>
      <td id="T_b92ab_row19_col4" class="data row19 col4" >0</td>
      <td id="T_b92ab_row19_col5" class="data row19 col5" >0</td>
      <td id="T_b92ab_row19_col6" class="data row19 col6" >1</td>
      <td id="T_b92ab_row19_col7" class="data row19 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row20_col0" class="data row20 col0" >0</td>
      <td id="T_b92ab_row20_col1" class="data row20 col1" >0</td>
      <td id="T_b92ab_row20_col2" class="data row20 col2" >0</td>
      <td id="T_b92ab_row20_col3" class="data row20 col3" >1</td>
      <td id="T_b92ab_row20_col4" class="data row20 col4" >0</td>
      <td id="T_b92ab_row20_col5" class="data row20 col5" >1</td>
      <td id="T_b92ab_row20_col6" class="data row20 col6" >0</td>
      <td id="T_b92ab_row20_col7" class="data row20 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row21_col0" class="data row21 col0" >0</td>
      <td id="T_b92ab_row21_col1" class="data row21 col1" >0</td>
      <td id="T_b92ab_row21_col2" class="data row21 col2" >0</td>
      <td id="T_b92ab_row21_col3" class="data row21 col3" >1</td>
      <td id="T_b92ab_row21_col4" class="data row21 col4" >0</td>
      <td id="T_b92ab_row21_col5" class="data row21 col5" >1</td>
      <td id="T_b92ab_row21_col6" class="data row21 col6" >0</td>
      <td id="T_b92ab_row21_col7" class="data row21 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row22_col0" class="data row22 col0" >0</td>
      <td id="T_b92ab_row22_col1" class="data row22 col1" >0</td>
      <td id="T_b92ab_row22_col2" class="data row22 col2" >0</td>
      <td id="T_b92ab_row22_col3" class="data row22 col3" >1</td>
      <td id="T_b92ab_row22_col4" class="data row22 col4" >0</td>
      <td id="T_b92ab_row22_col5" class="data row22 col5" >1</td>
      <td id="T_b92ab_row22_col6" class="data row22 col6" >1</td>
      <td id="T_b92ab_row22_col7" class="data row22 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row23_col0" class="data row23 col0" >0</td>
      <td id="T_b92ab_row23_col1" class="data row23 col1" >0</td>
      <td id="T_b92ab_row23_col2" class="data row23 col2" >0</td>
      <td id="T_b92ab_row23_col3" class="data row23 col3" >1</td>
      <td id="T_b92ab_row23_col4" class="data row23 col4" >0</td>
      <td id="T_b92ab_row23_col5" class="data row23 col5" >1</td>
      <td id="T_b92ab_row23_col6" class="data row23 col6" >1</td>
      <td id="T_b92ab_row23_col7" class="data row23 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row24_col0" class="data row24 col0" >0</td>
      <td id="T_b92ab_row24_col1" class="data row24 col1" >0</td>
      <td id="T_b92ab_row24_col2" class="data row24 col2" >0</td>
      <td id="T_b92ab_row24_col3" class="data row24 col3" >1</td>
      <td id="T_b92ab_row24_col4" class="data row24 col4" >1</td>
      <td id="T_b92ab_row24_col5" class="data row24 col5" >0</td>
      <td id="T_b92ab_row24_col6" class="data row24 col6" >0</td>
      <td id="T_b92ab_row24_col7" class="data row24 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row25_col0" class="data row25 col0" >0</td>
      <td id="T_b92ab_row25_col1" class="data row25 col1" >0</td>
      <td id="T_b92ab_row25_col2" class="data row25 col2" >0</td>
      <td id="T_b92ab_row25_col3" class="data row25 col3" >1</td>
      <td id="T_b92ab_row25_col4" class="data row25 col4" >1</td>
      <td id="T_b92ab_row25_col5" class="data row25 col5" >0</td>
      <td id="T_b92ab_row25_col6" class="data row25 col6" >0</td>
      <td id="T_b92ab_row25_col7" class="data row25 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row26_col0" class="data row26 col0" >0</td>
      <td id="T_b92ab_row26_col1" class="data row26 col1" >0</td>
      <td id="T_b92ab_row26_col2" class="data row26 col2" >0</td>
      <td id="T_b92ab_row26_col3" class="data row26 col3" >1</td>
      <td id="T_b92ab_row26_col4" class="data row26 col4" >1</td>
      <td id="T_b92ab_row26_col5" class="data row26 col5" >0</td>
      <td id="T_b92ab_row26_col6" class="data row26 col6" >1</td>
      <td id="T_b92ab_row26_col7" class="data row26 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row27_col0" class="data row27 col0" >0</td>
      <td id="T_b92ab_row27_col1" class="data row27 col1" >0</td>
      <td id="T_b92ab_row27_col2" class="data row27 col2" >0</td>
      <td id="T_b92ab_row27_col3" class="data row27 col3" >1</td>
      <td id="T_b92ab_row27_col4" class="data row27 col4" >1</td>
      <td id="T_b92ab_row27_col5" class="data row27 col5" >0</td>
      <td id="T_b92ab_row27_col6" class="data row27 col6" >1</td>
      <td id="T_b92ab_row27_col7" class="data row27 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row28_col0" class="data row28 col0" >0</td>
      <td id="T_b92ab_row28_col1" class="data row28 col1" >0</td>
      <td id="T_b92ab_row28_col2" class="data row28 col2" >0</td>
      <td id="T_b92ab_row28_col3" class="data row28 col3" >1</td>
      <td id="T_b92ab_row28_col4" class="data row28 col4" >1</td>
      <td id="T_b92ab_row28_col5" class="data row28 col5" >1</td>
      <td id="T_b92ab_row28_col6" class="data row28 col6" >0</td>
      <td id="T_b92ab_row28_col7" class="data row28 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row29_col0" class="data row29 col0" >0</td>
      <td id="T_b92ab_row29_col1" class="data row29 col1" >0</td>
      <td id="T_b92ab_row29_col2" class="data row29 col2" >0</td>
      <td id="T_b92ab_row29_col3" class="data row29 col3" >1</td>
      <td id="T_b92ab_row29_col4" class="data row29 col4" >1</td>
      <td id="T_b92ab_row29_col5" class="data row29 col5" >1</td>
      <td id="T_b92ab_row29_col6" class="data row29 col6" >0</td>
      <td id="T_b92ab_row29_col7" class="data row29 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row30_col0" class="data row30 col0" >0</td>
      <td id="T_b92ab_row30_col1" class="data row30 col1" >0</td>
      <td id="T_b92ab_row30_col2" class="data row30 col2" >0</td>
      <td id="T_b92ab_row30_col3" class="data row30 col3" >1</td>
      <td id="T_b92ab_row30_col4" class="data row30 col4" >1</td>
      <td id="T_b92ab_row30_col5" class="data row30 col5" >1</td>
      <td id="T_b92ab_row30_col6" class="data row30 col6" >1</td>
      <td id="T_b92ab_row30_col7" class="data row30 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row31_col0" class="data row31 col0" >0</td>
      <td id="T_b92ab_row31_col1" class="data row31 col1" >0</td>
      <td id="T_b92ab_row31_col2" class="data row31 col2" >0</td>
      <td id="T_b92ab_row31_col3" class="data row31 col3" >1</td>
      <td id="T_b92ab_row31_col4" class="data row31 col4" >1</td>
      <td id="T_b92ab_row31_col5" class="data row31 col5" >1</td>
      <td id="T_b92ab_row31_col6" class="data row31 col6" >1</td>
      <td id="T_b92ab_row31_col7" class="data row31 col7" >1</td>
    </tr>
    <tr>
      <td id="T_b92ab_row32_col0" class="data row32 col0" >0</td>
      <td id="T_b92ab_row32_col1" class="data row32 col1" >0</td>
      <td id="T_b92ab_row32_col2" class="data row32 col2" >1</td>
      <td id="T_b92ab_row32_col3" class="data row32 col3" >0</td>
      <td id="T_b92ab_row32_col4" class="data row32 col4" >0</td>
      <td id="T_b92ab_row32_col5" class="data row32 col5" >0</td>
      <td id="T_b92ab_row32_col6" class="data row32 col6" >0</td>
      <td id="T_b92ab_row32_col7" class="data row32 col7" >0</td>
    </tr>
    <tr>
      <td id="T_b92ab_row33_col0" class="data row33 col0" >0</td>
      <td id="T_b92ab_row33_col1" class="data row33 col1" >0</td>
      <td id="T_b92ab_row33_col2" class="data row33 col2" >1</td>
      <td id="T_b92ab_row33_col3" class="data row33 col3" >0</td>
      <td id="T_b92ab_row33_col4" class="data row33 col4" >0</td>
      <td id="T_b92ab_row33_col5" class="data row33 col5" >0</td>

#### Notation
The obvious precise mathematical notation for us to represent the value of a particular byte is that of a vector of binary digits:

$$
[b_7 b_6 b_5 b_4 b_3 b_2 b_1 b_0] \; \text{where} \; b_i \in \{0,1\}
$$  

and where its value, as a non-negative integer, is the positional sum of powers of two as follows:

$$ 
\sum_{i=0}^{7} b_i \times 2^{i}
$$

It is worth remembering that in a computer every byte is a unique array at a particular location in the computer and that a location can only store a single value at a time (<a href="#fig:8switches">A byte as 8 switches</a>).  We represent it's value as a  vector of eight binary digits.   We will use capital script letters refer to a particular array. Further to allows us to be precise about units greater than 8 bits we will subscript the letter with the length in bits at the location we are referring too.  Eg $X_{16}$ means a location $X$ composed of $16$ bits or two bytes.  We will use a vector of lower case script letters with a subscript to refer to bits that compose a particular array.  Eg 

$$ 
X_{16} \equiv [ x_{15} x_{14} x_{13} x_{12} x_{11} x_{10} x_{9} x_{8} x_{7} x_{6} x_{5} x_{4} x_{3} x_{2} x_{2} x_{1} x_{0} ] 
$$

The value of an $n$-bit array as a non-negative integer is (remember the bit index is one less than then length):

$$ 
\sum_{i=0}^{n-1} b_i \times 2^{i}
$$

Bit $b_{n-1}$, the left most bit is said to be the most significant and the right most bit, $b_0$, the least significant.

When we want to indicate that we are assigning a particular value to the bits of a location we will use a left arrow.  Eg.  

$$
X_{16} \leftarrow [01110000010001111]
$$

means we are assigning the the respective bits of $X$ to the corresponding binary digits.  Similarly 

$$ 
X_{16} \leftarrow Y_{16} 
$$

means we are assign the bits of $X$ to the corresponding current values of the bits $Y$.  It is important to remember that in such an assignment all prior values of the bits of $X$ are overwritten and the bits of $Y$ are unchanged.

If there is ambiguity we will use `0b` as a prefix to a value to indicate that it is in binary notation eg. `0b10`.

#### Nibbles and Hexidecimal

As you can see it is unwieldy to constantly use the notation of binary, base two, digits to refer to particular patterns instead we tend to use hexadecimal (base 16) to refer to a specific binary value.   You will often see the short form **hex** to refer to hexadecimal notation where the digits corresponded to the following 16 characters $0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F$.  Each position in a value in hex notation represents a power of 16.
Further to avoid ambiguity  `0x` is used as a prefix to indicate that a value is being expressed in hex.  Eg `0x11` indicates a the hexadecimal value that corresponds to $1\times16^{1} + 1\times16^{0}$. More generally given an $n$ digit hex number the value would be:

$$
\sum_{i=0}^{n-1}16^{i}
$$

Part of the reason we use hex is due to the following *nice* relationship --   A single hex digit, can be used
to represent the value of four bits.  We call four bits a nibble.  The following table shows the mapping of the 16 hex digits to its corresponding 4 bit nibble value.

In [17]:
md=displayBytes(bytes=[[i] for i in range(16)],
             td_font_size="1em", 
             th_font_size="1em", 
             numbits=4, 
             columns=["[<em>b<sub>3</sub></em>", "<em>b<sub>2</sub></em>",
                      "<em>b<sub>1</sub></em>", "<em>b<sub>0</sub></em>]"], 
             labels=[format(i,"1X")for i in range(16)], 
             labelstitle="HEX", 
             center=True,
             disp=False)
display(Markdown(MDBox(md, h="100%", overflow="none", title='<center id="table:hex" style="font-size:.8em">Table: Hexadecimal to nibble values</center>')))

<center id="table:hex" style="font-size:.8em">Table: Hexadecimal to nibble values</center>
<div style="width:100%; height:100%; font-size:inherit; overflow: none;" >

<style type="text/css">
#T_2bbd2 td {
  border: 4px solid #cccccc;
  font-size: 1em;
  text-align: center;
  overflow-x: hidden;
}
#T_2bbd2 th {
  font-size: 1em;
  text-align: center;
  font-weight: bold;
  border: solid #cccccc;
  color: black;
  background-color: white;
}
#T_2bbd2 td:hover {
  background-color: white;
  color: black;
}
#T_2bbd2 tr:hover {
  background-color: #11cccccc;
  border: 4px solid red;
}
#T_2bbd2 th:hover {
  border: solid red;
}
#T_2bbd2 thead tr:nth-child(1) th {
  position: sticky;
  background-color: white;
  top: 0px;
  z-index: 2;
}
#T_2bbd2  {
  margin-left: auto;
  margin-right: auto;
}
</style>
<table id="T_2bbd2">
  <thead>
    <tr>
      <th class="index_name level0" >HEX</th>
      <th id="T_2bbd2_level0_col0" class="col_heading level0 col0" >[<em>b<sub>3</sub></em></th>
      <th id="T_2bbd2_level0_col1" class="col_heading level0 col1" ><em>b<sub>2</sub></em></th>
      <th id="T_2bbd2_level0_col2" class="col_heading level0 col2" ><em>b<sub>1</sub></em></th>
      <th id="T_2bbd2_level0_col3" class="col_heading level0 col3" ><em>b<sub>0</sub></em>]</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_2bbd2_level0_row0" class="row_heading level0 row0" >0</th>
      <td id="T_2bbd2_row0_col0" class="data row0 col0" >0</td>
      <td id="T_2bbd2_row0_col1" class="data row0 col1" >0</td>
      <td id="T_2bbd2_row0_col2" class="data row0 col2" >0</td>
      <td id="T_2bbd2_row0_col3" class="data row0 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row1" class="row_heading level0 row1" >1</th>
      <td id="T_2bbd2_row1_col0" class="data row1 col0" >0</td>
      <td id="T_2bbd2_row1_col1" class="data row1 col1" >0</td>
      <td id="T_2bbd2_row1_col2" class="data row1 col2" >0</td>
      <td id="T_2bbd2_row1_col3" class="data row1 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row2" class="row_heading level0 row2" >2</th>
      <td id="T_2bbd2_row2_col0" class="data row2 col0" >0</td>
      <td id="T_2bbd2_row2_col1" class="data row2 col1" >0</td>
      <td id="T_2bbd2_row2_col2" class="data row2 col2" >1</td>
      <td id="T_2bbd2_row2_col3" class="data row2 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row3" class="row_heading level0 row3" >3</th>
      <td id="T_2bbd2_row3_col0" class="data row3 col0" >0</td>
      <td id="T_2bbd2_row3_col1" class="data row3 col1" >0</td>
      <td id="T_2bbd2_row3_col2" class="data row3 col2" >1</td>
      <td id="T_2bbd2_row3_col3" class="data row3 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row4" class="row_heading level0 row4" >4</th>
      <td id="T_2bbd2_row4_col0" class="data row4 col0" >0</td>
      <td id="T_2bbd2_row4_col1" class="data row4 col1" >1</td>
      <td id="T_2bbd2_row4_col2" class="data row4 col2" >0</td>
      <td id="T_2bbd2_row4_col3" class="data row4 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row5" class="row_heading level0 row5" >5</th>
      <td id="T_2bbd2_row5_col0" class="data row5 col0" >0</td>
      <td id="T_2bbd2_row5_col1" class="data row5 col1" >1</td>
      <td id="T_2bbd2_row5_col2" class="data row5 col2" >0</td>
      <td id="T_2bbd2_row5_col3" class="data row5 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row6" class="row_heading level0 row6" >6</th>
      <td id="T_2bbd2_row6_col0" class="data row6 col0" >0</td>
      <td id="T_2bbd2_row6_col1" class="data row6 col1" >1</td>
      <td id="T_2bbd2_row6_col2" class="data row6 col2" >1</td>
      <td id="T_2bbd2_row6_col3" class="data row6 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row7" class="row_heading level0 row7" >7</th>
      <td id="T_2bbd2_row7_col0" class="data row7 col0" >0</td>
      <td id="T_2bbd2_row7_col1" class="data row7 col1" >1</td>
      <td id="T_2bbd2_row7_col2" class="data row7 col2" >1</td>
      <td id="T_2bbd2_row7_col3" class="data row7 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row8" class="row_heading level0 row8" >8</th>
      <td id="T_2bbd2_row8_col0" class="data row8 col0" >1</td>
      <td id="T_2bbd2_row8_col1" class="data row8 col1" >0</td>
      <td id="T_2bbd2_row8_col2" class="data row8 col2" >0</td>
      <td id="T_2bbd2_row8_col3" class="data row8 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row9" class="row_heading level0 row9" >9</th>
      <td id="T_2bbd2_row9_col0" class="data row9 col0" >1</td>
      <td id="T_2bbd2_row9_col1" class="data row9 col1" >0</td>
      <td id="T_2bbd2_row9_col2" class="data row9 col2" >0</td>
      <td id="T_2bbd2_row9_col3" class="data row9 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row10" class="row_heading level0 row10" >A</th>
      <td id="T_2bbd2_row10_col0" class="data row10 col0" >1</td>
      <td id="T_2bbd2_row10_col1" class="data row10 col1" >0</td>
      <td id="T_2bbd2_row10_col2" class="data row10 col2" >1</td>
      <td id="T_2bbd2_row10_col3" class="data row10 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row11" class="row_heading level0 row11" >B</th>
      <td id="T_2bbd2_row11_col0" class="data row11 col0" >1</td>
      <td id="T_2bbd2_row11_col1" class="data row11 col1" >0</td>
      <td id="T_2bbd2_row11_col2" class="data row11 col2" >1</td>
      <td id="T_2bbd2_row11_col3" class="data row11 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row12" class="row_heading level0 row12" >C</th>
      <td id="T_2bbd2_row12_col0" class="data row12 col0" >1</td>
      <td id="T_2bbd2_row12_col1" class="data row12 col1" >1</td>
      <td id="T_2bbd2_row12_col2" class="data row12 col2" >0</td>
      <td id="T_2bbd2_row12_col3" class="data row12 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row13" class="row_heading level0 row13" >D</th>
      <td id="T_2bbd2_row13_col0" class="data row13 col0" >1</td>
      <td id="T_2bbd2_row13_col1" class="data row13 col1" >1</td>
      <td id="T_2bbd2_row13_col2" class="data row13 col2" >0</td>
      <td id="T_2bbd2_row13_col3" class="data row13 col3" >1</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row14" class="row_heading level0 row14" >E</th>
      <td id="T_2bbd2_row14_col0" class="data row14 col0" >1</td>
      <td id="T_2bbd2_row14_col1" class="data row14 col1" >1</td>
      <td id="T_2bbd2_row14_col2" class="data row14 col2" >1</td>
      <td id="T_2bbd2_row14_col3" class="data row14 col3" >0</td>
    </tr>
    <tr>
      <th id="T_2bbd2_level0_row15" class="row_heading level0 row15" >F</th>
      <td id="T_2bbd2_row15_col0" class="data row15 col0" >1</td>
      <td id="T_2bbd2_row15_col1" class="data row15 col1" >1</td>
      <td id="T_2bbd2_row15_col2" class="data row15 col2" >1</td>
      <td id="T_2bbd2_row15_col3" class="data row15 col3" >1</td>
    </tr>
  </tbody>
</table>


</div>

As such it is easy to express an 8 bit value, as two hex digits, giving us a more concise notation.    Although it might not seem like it now it become natural, as you work in hex, to associate the hex digits with its corresponding four bit binary pattern.  In time you will be able to see in your mind various mappings.  For example `0x3` "maps" too the *right* most two bits *on*, `0x7` "maps" to all bits *on* except the left most bit (lower 3 bits *on*), `8` "maps" to only the *high* bit *on*, `E` "maps" to all bits *on* except the *right* most bit, and `F` "maps" to all bits *on*.  And others patterns in time  will get ingrained in your mind.  Notice how we also associate relationships like *left* and *upper*, and *right* and *lower*, as well as `1` and *on* and `0` and *off*.   These all capture the fact that we use bit patterns for many different things. 

To convert values simple use the <a href="#table:hex">hex to nibble table</a>.  For example to covert the following binary value

In [18]:
X=np.uint8(0xae)
XL=np.bitwise_and(X,0xf)
XH=np.bitwise_and(np.right_shift(X,4),0xf)
displayBytes(bytes=[[X]], td_font_size="1em", th_font_size="1em")

we break it down into the following two nibbles

In [19]:
displayBytes(bytes=[[XH]], 
             td_font_size="1em", 
             th_font_size="1em", 
             numbits=4,
             columns=["[<em>b<sub>7</sub></em>", "<em>b<sub>6</sub></em>",
                      "<em>b<sub>5</sub></em>", "<em>b<sub>4</sub></em>]"]) 
displayBytes(bytes=[[XL]],
             td_font_size="1em", 
             th_font_size="1em", 
             numbits=4,
             columns=["[<em>b<sub>3</sub></em>", "<em>b<sub>2</sub></em>",
                      "<em>b<sub>1</sub></em>", "<em>b<sub>0</sub></em>]"])

converting each nibble to their corresponding hex digit we get `0xAE`

Depsite the heavy use will will make of hex notation remember, however, the hardware in reality does not store or operate on “Hex" rather it is just a convient generic notation for us to express a particular binary value.

### Registers and Memory

In the von <a href="">Neumann computer architecture</a> there are two regions in the computer that we as general programmers must concern ourselves with.  The CPU and Memory. 

#### Registers

The CPU contains a set of byte locations, called **Registers**, which the operations of the CPU can refer to.  As discussed in the <a href="">introduction</a>, CPU operations themselves are encoded as binary patterns. Part of the code for an operation specifies which registers the operation works with.  There are three categories of operations that 1) assign the value of a particular register, 2) peform some logical or mathematical operation of values, and 3) direct what location in memory the next operation code should be loaded from.    The serve Registers as the core locations in the computer that we use to do work.  

Generically the entire set of registers in the CPU are called the Register File.  The subset that we use for general operations are called the **General Purpose Registers** (**GPRS**). The other registers of the Register File either are reserved for special use by the CPU or by the operating system software and unsurprisingly often called **Special Purpose Registers** (**SPRS**). Each CPU vendor specifies a set of symbolic names that use to indentify a particular register.

For example on Intel 64Bit Processors sixteen 64 bit GPRS are; `RAX`, `RBX`, `RCX`, `RDX`, `RDI`, `RSI`, `RBP`, `RSP`, `R8`, `R9`, `R10`, `R11`, `R12`, `R13`, `R14`, `R15` (see 3.4.1.1 of the Intel 64 and IA-32 Architectures Software Developer’s Manual, Volume 1).  On ARM Arch64 Bit Processors there are thirty one 64 bit GPRS that are uniformly named `X0..X30` (see <a href="https://developer.arm.com/documentation/102374/0101/Registers-in-AArch64---general-purpose-registers">Register in AArch64</a>).  An on the old 8 bit 6502 processor there is only 3 GPRS; `X`, `Y`, and `A`.

On modern processors like 64Bit Intel and ARM processors the GPRS are all 64 bits, 8 bytes, in length.  However, the processors also provide GPRS of smaller lengths which refer to subcomponents of the 64bit registters.  For example on 64bit ARM processors the names `W0..W30` refer to 32 bit, 4 byte, length registers which are formed from the lower 32bits of the correspomding 64 bit `X` register.  Intel Processors have a much more diverse and subtle set of smaller sized regiters that are composed of the sub bytes of the 64 bit GPRS.  The <a href="#intelGPRBreakdown">figure</a> below illustrates and example of the Intel names for smaller registers that refer to bytes of a larger register.

In [20]:
display(Markdown(htmlFig("../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.034.png", id="fig:intelGPRBreakdown", width="90%",
                         caption="Fig: Example of how the INTEL GPRS are broken down.  Note one must carefully read the manual as the breakdown is not the same for all the GPRS.")))

<!-- produced by:
htmlFig("[{'src': '../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.034.png'}]",
        id="fig:intelGPRBreakdown",
        align="center",
        width="90%",
        margin="auto auto auto auto",
        caption="Fig: Example of how the INTEL GPRS are broken down.  Note one must carefully read the manual as the breakdown is not the same for all the GPRS.",
        captionalign="left")
-->
<table id="fig:intelGPRBreakdown" align="center" width="90%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: auto auto auto auto">
    <tr style="padding: 0; margin: 0;">
        <td colspan="1" width="100%" style="padding: 0; margin: 0 0 0 0; background-color:inherit;">
            <div style="padding: 0; margin: 0 0 0 0;">
              <figure style="padding: 0; margin: 0 0 0 0; width:100%;">
                   <img src="../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.034.png" width="100%" style="padding: 0; margin: 0;">
                </figure>
            </div>
        </td>
    </tr>
    <caption align="bottom" style="text-align: left; padding: 0; margin: 0;" >
          <i>Fig: Example of how the INTEL GPRS are broken down.  Note one must carefully read the manual as the breakdown is not the same for all the GPRS.</i>
    </caption>
</table>

##### Notation

When we want to name a register location we will extend our notation as follows.  If we are referring to a particular processor vendor register we will use the name subscripted with the length to avoid confusion.  For example to note that we are assigning the value in the Intel 64 bit `RAX` register to `RBX` we would write $\text{RBX}_{64} \leftarrow \text{RAX}_{64}$.  Similarly for in the case of ARM the we would write $\text{X2}_{64} \leftarrow \text{X1}_{64}$.  If we are generically referring to registers we will use capital scripts notation subscripted by a specific length as follows $R4_{32} \leftarrow R5_{32}$.

##### GDB Display and Set Registers

<div style="background-color:LimeGreen;">
<img style="display: inline; margin: auto auto auto auto;" align="left" width="40px" src="../images/do.svg">
    
**GDB:** The following is some basic gdb commands for working with registers.  We will learn more advanced syntax later but this will get us going.
    
- `p /t $<register name>` : print out the current value of a register in binary notation
- `set $<register name>=0b<binary value` : to set a register's value in binary notation 
- `p /t $<register name>` : print out the current value of a register in hex
- `set $<register name>=0x<hex value>` : to set a register's value in hex notation
    
As we see in <a href="#fig:intelGPRBreakdown">Intel Register Figure</a>.  Each register name 
references an exact size in bytes.  Eg. `rax` is a 64 bit (8 byte) register so setting its value is 
an 8 byte assignment vs `eax` is 32 bits (4 bytes) in size, being a 4 byte assignment.
GDB will add leading zeros as necessary to pad out any value that is smaller than the size of the
register.  Similarly gdb will ignore all lead values that are beyond the size of the register.

The gdb command `p` stands for print.   GDB has many built in encodings and notations that it understands.  In the above the `/t` and` /x` specified the format, notation, we wanted to print the value in.  More generally the format syntax is very rich. The print command format syntax is a restricted set of the  examine memory command (`x`) format syntax.  We will discuss the examine memory when we discuss working with memory in GDB later in this chapter.  Remember you can use the `help` command in gdb to learn more about an command.   However, the `help` documentation can be a little overwhelming at first.  
    
Open the following to see an x86-64 example session using these commands (we encourage to try this yourself and to play around).
</div>

In [21]:
display(Markdown('''
0. assemble and link the empty.s code shown
1. `gdb`: Start gdb
2. `file empty`: Open the `empty` executable
3. `b _start`: Set a breakpoint at _start
4. `run`: Start/run "inferior process" from executable
5. When execution stops at breakpoint
6 `p /t $rax`: print register rax in binary
7. `set $rax=0b10101111`: set register rax to `10101111` in binary (leading zeros are added automatically)
8. `p /t $rax`: print rax again in binary
9. `p /x $rax`: print rax in hex
10. `set $rax=0xfeedface` set register rax
11. `set $rbx=0xdeadbeef` set register rbx
12. `p /x {$rax, $rbx}`
13. `p /t {$rax, $rbx}`
14. `set $cl=0xcafe` set byte sized cl register with a two byte sized value
15. `p /x {$cl, $cx, $ecx, $rcx}`
'''))
display(Markdown(FileCodeBox(
    file=exdir + "/empty256.s", 
    lang="gas", 
    title="<b>CODE: Source to create an `empty` process with 256 bytes of zeros to play with in gdb</b>",
    h="10em", 
    w="100%"
)))
TermShellCmd("make clean", cwd=exdir, prompt='')
display(Markdown("**Commands to assemble and link**"))
display(TermShellCmd("make ASFLAGS='' LDFLAGS='' empty256", cwd=exdir, prompt='',height="100%"))
display(Markdown("**GDB Session**"))
gdbCmds('''file empty256
break _start
run
p /t $rax
set $rax = 0b10101111
p /t $rax
p /x $rax
set $rax=0xfeedface
set $rbx=0xdeadbeef
p /x {$rax, $rbx}
p /t {$rax, $rbx}
set $cl=0xcafe
p /x $cl
p /x $cx
p /x $ecx
p /x $rcx
''', cwd=exdir, height="10em")

0. assemble and link the empty.s code shown
1. `gdb`: Start gdb
2. `file empty`: Open the `empty` executable
3. `b _start`: Set a breakpoint at _start
4. `run`: Start/run "inferior process" from executable
5. When execution stops at breakpoint
6 `p /t $rax`: print register rax in binary
7. `set $rax=0b10101111`: set register rax to `10101111` in binary (leading zeros are added automatically)
8. `p /t $rax`: print rax again in binary
9. `p /x $rax`: print rax in hex
10. `set $rax=0xfeedface` set register rax
11. `set $rbx=0xdeadbeef` set register rbx
12. `p /x {$rax, $rbx}`
13. `p /t {$rax, $rbx}`
14. `set $cl=0xcafe` set byte sized cl register with a two byte sized value
15. `p /x {$cl, $cx, $ecx, $rcx}`

<b>CODE: Source to create an `empty` process with 256 bytes of zeros to play with in gdb</b>
<div style="width:100%; height:10em; font-size:inherit; overflow: auto;" >


``` gas
	.intel_syntax noprefix        # syntax directive
	.text                         # linker section <directive>

	.global _start                # export symbol _start to linker
_start:                               # start symbol
	.fill 256, 1, 0x00            # https://sourceware.org/binutils/docs/as/Fill.html

```


</div>

**Commands to assemble and link**

Output(layout=Layout(border='1px solid black', height='100%', overflow_y='scroll'))

**GDB Session**

Output(layout=Layout(border='1px solid black', height='10em', overflow_y='scroll'))

#### Memory, addresses and address expressions

In a von Neumann architecture the Memory of the computer forms a large fixed size array of bytes which is directly connected to the CPU.  Critically, the CPU can transfer values from and to its registers and locations in memory.  Unlike registers there is no hardware specific symbolic names for the locations.  Rather we identify which byte of memory by specifying its array index, which we call its **address**.    

##### Notation
Notationally we will use $M[\text{<expr>}]$ to refer to a  specific byte in memory, where $\text{<expr>}$ is an **address expression** who's value is the address we are referring too.  In the simplest from this it might just be a number in some base notation eg. $M[\text{0xFFF0}]$ refers to the memory location of the byte at address $\text{0xFFF0}$.  We might also use symbols such as $\alpha$ or $\beta$, to mean some particular address but who's exact value is not of concern eg.  $M[\alpha]$.  It is important to note that an address is just a number ranging from 0 to the  maximum number of bytes of memory minus one.  This range is often called an address space as it defines the range of memory addresses that one can refer too. On a computer that supports a $2^{64}$ address space the address values can range from $0$ to $2^{64}-1$ or in hex $\text{0x0}$ to $\text{0xffffffffffffffff}$.  

Given that an address is just a number it is natural for an address expression to be simple arithmetic expressions eg. $M[\alpha + 16]$ means the memory location who's address is $\alpha$ plus 16.  Similarly $M[\beta + 8 * \alpha]$ mean the memory location who's address is $\beta$ plus eight times $\alpha$.  It will also be common for us to use the value of registers in memory address expressions such as $M[\text{RAX}_{64} + 4 * \text{RDI}_{64} + \text{0xdeadbeef}]$ which means the location which is the current value of $\text{RAX}$ plus 4 times the current value of $\text{RDI}$.  

Finally we may want to work with a group of bytes of a length $w$ in bits starting at a particular address.  Like with with registers we will use a subscript to indicate the length  eg. $M[\alpha]_{16}$ or $M[\alpha]_{32}$ or $M[\alpha]_{64}$ respectively meaning the 2, 4 and 8 bytes starting at location $\alpha$ and proceeding the the next larger locations as needed.  If not length is given then we implicitly mean a length of 8 bits (1 byte). 

As before we will use the $\leftarrow$ to indicate assignment: eg.

- $M[\text{0xdeadbeef}] \leftarrow \text{0x1a}$ means set the bits of the byte at memory address $\text{0xdeadbeef}$ to the value of $\text{0x1a}$.  
- $M[\alpha + 8 * R13_{64}]_{64} \leftarrow R5_{64}$  means set the bits of the 8 bytes at the memory address who's value is $\alpha$ plus eight times the 8 bytes value of register $R13$ to the 8 byte value of register $R5$.
- $\text{RAX}_{64} \leftarrow M[\text{RIP}_{64} + -42]_{64}$ means set the 64 bit value of the $\text{RAX}$ register to 64 bit value at memory whose address  is the current 64 bit value of the $\text{RIP}$ register minus 42.

##### Byte Geometry

Given that we have settled on the byte as the standard unit of storage we unsurprisingly measure capacity of devices in bytes.  For example my computer has 32 GigaBytes of memory and a 1 TeraByte Solid State Drive.  Similarly, when we encode information we think of the encoded information has have a length in bytes.  As a matter of fact one can go further say that information has a geometry in the form of a position (location) and size (length in bytes).

We will find that it can be very useful to learn how to visualization the geometry of our software both to understand how it is being represented and how and why it works the way it does.

##### "Endianness"

As CPU's evolved to have registers that are bigger than a single byte a decision needed to be made regarding the order that is used to store the bytes of a register when it is transferred to or from memory.

For example if we want to do the following: 
$M[\alpha]_{64} \leftarrow R1_{64}$

We must transfer the 64 bits, 8 bytes, of $R1$ to memory starting at address $\alpha$.    The first choice that was made was to store the bytes of the register in increasing address order.  That is to say the bytes of the Register will be stored at the bytes in memory whose addresses are increase.  So in our example the 8 bytes of $R1$ will stored at: $M[\alpha]_{8}$, $M[\alpha+1]_{8}$, $M[\alpha+2]_{8}$, $M[\alpha+3]_{8}$, $M[\alpha+4]_{8}$, $M[\alpha+5]_{8}$, $M[\alpha+6]_{8}$, and $M[\alpha+7]_{8}$.
While there are many possible order that could be 
used two standard "endiannesses" that developed; 1) little endian, and 2) big endian.

Before we can present the two standard orders we must first have a convention for referring the the bytes of multi-byte value.  We use the mathematical notion of significance.

###### Most and Least Significant Bytes

In [22]:
display(Markdown(htmlFig("../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.039.png", 
        id="fig:bytesig", 
        width="60%",
        caption="Figure: Byte Significance", 
        captionalign="left")))

<!-- produced by:
htmlFig("[{'src': '../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.039.png'}]",
        id="fig:bytesig",
        align="center",
        width="60%",
        margin="auto auto auto auto",
        caption="Figure: Byte Significance",
        captionalign="left")
-->
<table id="fig:bytesig" align="center" width="60%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: auto auto auto auto">
    <tr style="padding: 0; margin: 0;">
        <td colspan="1" width="100%" style="padding: 0; margin: 0 0 0 0; background-color:inherit;">
            <div style="padding: 0; margin: 0 0 0 0;">
              <figure style="padding: 0; margin: 0 0 0 0; width:100%;">
                   <img src="../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.039.png" width="100%" style="padding: 0; margin: 0;">
                </figure>
            </div>
        </td>
    </tr>
    <caption align="bottom" style="text-align: left; padding: 0; margin: 0;" >
          <i>Figure: Byte Significance</i>
    </caption>
</table>

Given that we think of a binary value as a vector of bits it is natural to think of them as a vector of bytes with the same notion of significance of bits.  As illustrated above.

###### Little Endian

In [23]:
display(Markdown(htmlFig("../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.040.png", 
        id="fig:litteendian", 
        width="60%",
        caption="Figure: 'Little Endian' byte ordering.", 
        captionalign="left")))

<!-- produced by:
htmlFig("[{'src': '../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.040.png'}]",
        id="fig:litteendian",
        align="center",
        width="60%",
        margin="auto auto auto auto",
        caption="Figure: 'Little Endian' byte ordering.",
        captionalign="left")
-->
<table id="fig:litteendian" align="center" width="60%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: auto auto auto auto">
    <tr style="padding: 0; margin: 0;">
        <td colspan="1" width="100%" style="padding: 0; margin: 0 0 0 0; background-color:inherit;">
            <div style="padding: 0; margin: 0 0 0 0;">
              <figure style="padding: 0; margin: 0 0 0 0; width:100%;">
                   <img src="../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.040.png" width="100%" style="padding: 0; margin: 0;">
                </figure>
            </div>
        </td>
    </tr>
    <caption align="bottom" style="text-align: left; padding: 0; margin: 0;" >
          <i>Figure: 'Little Endian' byte ordering.</i>
    </caption>
</table>

Little Endian byte ordering places the bytes in memory from least significant to most as illustrated in the figure above.

###### Big Endian

Unsurprisingly Big Endian byte ordering places values from most significant to least, the direct opposite of little endian ordering.

In [24]:
display(Markdown(htmlFig("../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.041.png", 
        id="fig:litteendian", 
        width="60%",
        caption="Figure: 'Big Endian' byte ordering.", 
        captionalign="left")))

<!-- produced by:
htmlFig("[{'src': '../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.041.png'}]",
        id="fig:litteendian",
        align="center",
        width="60%",
        margin="auto auto auto auto",
        caption="Figure: 'Big Endian' byte ordering.",
        captionalign="left")
-->
<table id="fig:litteendian" align="center" width="60%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: auto auto auto auto">
    <tr style="padding: 0; margin: 0;">
        <td colspan="1" width="100%" style="padding: 0; margin: 0 0 0 0; background-color:inherit;">
            <div style="padding: 0; margin: 0 0 0 0;">
              <figure style="padding: 0; margin: 0 0 0 0; width:100%;">
                   <img src="../images/ASSEMBLY-PGMI/ASSEMBLY-PGMI.041.png" width="100%" style="padding: 0; margin: 0;">
                </figure>
            </div>
        </td>
    </tr>
    <caption align="bottom" style="text-align: left; padding: 0; margin: 0;" >
          <i>Figure: 'Big Endian' byte ordering.</i>
    </caption>
</table>

###### Why Endianness matters to us

The CPU and computer more generally is configured to operate either in Little Endian or Big Endian byte ordering.  So for most programmers this detail is hidden from them.  But for those of us who want to look under the covers we need to be aware of which ordering the hardware is configured to use.  When we look at the raw bytes in memory and want to interpret a group of them, as a single vector, in the same way that the CPU will then we must know the ordering.  As we can see in the prior figures if we where to assume wrong ordering our interpretation of the value would be very different that the CPU's.  

It is also worth realizing that when we want to exchange raw binary information between computers we will also have to account for endianess.  This includes files that contain binary data that we want to work with on two different computers and binary data we exchange on the internet.  Programmers over the years have carefully chosen what order to use and then  have functions to convert the ordering to the data to the ordering used by the computer that you are accessing the data.
The wikipedia page on Endianness discusses both the implications on [files](https://en.wikipedia.org/wiki/Endianness#Files_and_filesystems) and [networking](https://en.wikipedia.org/wiki/Endianness#Networking)

##### Alignment

Like endianness there is another detail, called **alignment**,  that we will run into when looking and placing values in memory.

#### GDB and Memory

<div style="background-color:LimeGreen;">
<img style="display: inline; margin: auto auto auto auto;" align="left" width="40px" src="../images/do.svg"> 
    
**GDB:** GDB have very rich support for working with memory.  We can refer to addresses and various ways, examine memory at an address in many sizes and formats, and we can also set the value at memory locations.  It will take time for us to learn all this syntax.  But lets start with some basics commands to display addresses and examine the values starting at an address.
    
1. `p &<symbol>` will print the address of a name that we have used in our program that gets assigned an address by the linker.  Eg. "_start"
2. `x /1bt <address>` will print one byte in binary starting at the address specified
3. `x /1bx <address>` will print one byte in hex starting at the address specified
4.  In 2 and 3 above you can replace the `b` with  `h` or `w` or `g`.  This sets the size of unit to print b sets the unit size to 1 byte, h - 2 bytes, w -  4 bytes and g - 8 bytes.  Eg. `x /1gx` will print an one 8 byte value (unit) starting at the specified address.  GDB will take care of endianness for us.  
5.  In 2 and 3 above you can replace 1 (the number of units) with an integer $n$ to display $n$ units.
    
As we discuss more representations we will be introduce more complex formats for examining values. 
    
To set the value of a set of bytes starting at and address is a little more complicated as gdb uses syntax from the C programming language. Given that we have not yet covered the C programming language we will start slowly and introduce what we need as we go.  To start with lets see how we set 1, 2, 4 and 8 byte vectors starting at an address to hex and binary.  Like registers we use the set command but it is our job to tell gdb using a C type what size we are working with.  Respectively the types we will use are `unsigned char`, `unsigned short`, `unsigned int` and `unsigned long long`.   The following summarizes the syntax we will use for the moment:

1. `set {unsigned char}<address>=0x<hex value>` to set a single byte value starting at the specified address to the given value.
2. `set {unsigned short}<address=0x<hex value>` to set a two byte value starting at the specified address to the given value.
3. `set {unsigned int}<address=0x<hex value>` to set a four byte value starting at the specified address to the given value.  
4. `set {unsigned long long}<address=0x<hex value>` to set a eight byte value starting at the specified address to the given value.  
    
Like when setting registers gdb will add leading zeros or truncate the the right most digits if the size we specify is larger or smaller than the value we provide.   The following example gdb session illustrates using this syntax.

#### Fixed widths and their implications

It is very important to realize that when we refer to a register or memory location we must always keep in mind the length of the location.  As we saw each register has a fixed length specified by the CPU maker.  Eg. The INTEL registers $RAX$, $EAX$, $AX$, $AL$ are $64$, $32$, $16$ and $8$ bits long respectively and the ARM registers, $X0$ and $W0$ are $64$ and $32$ respectively.  When dealing with memory it our responsibility to explicitly transfer the right length in bits (to or from memory).  For example generically, on modern 64 bit cpus, given an address $\alpha$ and a 64 bit GPR such as $R3_{64}$ the following transfers are all typically possible.

1. $R3_{64}$ $\leftarrow$ $M[\alpha]_{8}$, $M[\alpha]_{8}$ $\leftarrow$ $R3_{64}$
2. $R3_{64}$ $\leftarrow$ $M[\alpha]_{16}$, $M[\alpha]_{16}$ $\leftarrow$ $R3_{64}$
3. $R3_{64}$ $\leftarrow$ $M[\alpha]_{32}$, $M[\alpha]_{32}$ $\leftarrow$ $R3_{64}$
4. $R3_{64}$ $\leftarrow$ $M[\alpha]_{64}$, $M[\alpha]_{64}$ $\leftarrow$ $R3_{64}$

There will be separate instructions for each.  As such it will always be our responsibility to specify the length of the transfer in addition to the direction and address!  When the sizes of a transfer do not match we must also be aware of what will happen.

##### Truncation 

Most CPUs when transferring a larger vector to a smaller vector eg. $R3_{8}$ $\leftarrow$ $R4_{32}$ or $R2_{16}$ $\leftarrow$ $M[\beta]_{64}$ the most significant bits of the value will be truncated to fit.  For example if we were transferring the following $32$ bit value:

In [43]:
X=np.uint32(0xFFFFFF03)
Y=np.uint8()
displayBytes(bytes=[[X]], numbits=32, columns=bitLabels(32), td_font_size="1em", th_font_size="1em")

##### Extension

### Representing Data vs Programs (Operations)

The two broad, and not necessarily mutually exclusive, categories of information we want to represent

Data
1 raw data - simple variables
- with standard interpretations.
Homogeneous arrays of simple values
2 complex data structures and abstract data types
Arrays of these, lists, trees, etc
Hard to separated these out without talking and the code to implement the interpretation

Code